# Generated by Django 5.0.14 on 2026-09-09 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, editable=False, max_length=30, unique=True
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("envoyee", "Envoyée"),
                            ("payee_partiel", "Payée partiellement"),
                            ("payee", "Payée"),
                            ("en_retard", "En retard"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_emission",
                    models.DateField(auto_now_add=True, verbose_name="Date d'émission"),
                ),
                (
                    "date_echeance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes / Note de détail"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factures",
                        to="partners.partner",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures",
                        to="dossiers.dossier",
                        verbose_name="Dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_frais",
                    models.CharField(
                        choices=[
                            ("honoraires", "Honoraires de transit"),
                            ("debours", "Débours"),
                            ("droits_taxes", "Droits et taxes"),
                            ("acconage", "Acconage"),
                            ("manutention", "Manutention"),
                            ("transport", "Transport"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de frais",
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Désignation"),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant"
                    ),
                ),
                ("date_paiement", models.DateField(verbose_name="Date de paiement")),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces (caisse)"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("effet", "Effet de commerce"),
                            ("autre", "Autre"),
                        ],
                        default="virement",
                        max_length=15,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Référence (chèque, virement...)",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, editable=False, max_length=30, unique=True
                    ),
                ),
                (
                    "type_devis",
                    models.CharField(
                        choices=[("devis", "Devis"), ("proforma", "Facture proforma")],
                        default="devis",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("envoye", "Envoyé"),
                            ("accepte", "Accepté"),
                            ("refuse", "Refusé"),
                            ("expire", "Expiré"),
                        ],
                        default="brouillon",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_validite",
                    models.DateField(
                        blank=True, null=True, verbose_name="Valide jusqu'au"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devis",
                        to="partners.partner",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devis",
                        to="dossiers.dossier",
                        verbose_name="Dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis / Proforma",
                "verbose_name_plural": "Devis & Proformas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_frais",
                    models.CharField(
                        choices=[
                            ("honoraires", "Honoraires de transit"),
                            ("debours", "Débours"),
                            ("droits_taxes", "Droits et taxes"),
                            ("acconage", "Acconage"),
                            ("manutention", "Manutention"),
                            ("transport", "Transport"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de frais",
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Désignation"),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="billing.quote",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_relance",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("telephone", "Téléphone"),
                            ("courrier", "Courrier"),
                            ("visite", "Visite"),
                        ],
                        max_length=15,
                        verbose_name="Type de relance",
                    ),
                ),
                ("date_relance", models.DateField(verbose_name="Date de la relance")),
                ("notes", models.TextField(blank=True, verbose_name="Compte-rendu")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relances",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relance",
                "verbose_name_plural": "Relances",
                "ordering": ["-date_relance"],
            },
        ),
    ]
