# Generated by Django 5.0.14 on 2026-09-09 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("treasury", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="compte",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="encaissements",
                to="treasury.cashaccount",
                verbose_name="Caisse / compte encaissé",
            ),
        ),
    ]
