# Generated by Django 5.0.14 on 2026-10-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_taux_tva"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="exonere_tva",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Exonéré de TVA"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="motif_exoneration",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                verbose_name="Motif de l'exonération",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="exonere_tva",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Exonéré de TVA"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="motif_exoneration",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                verbose_name="Motif de l'exonération",
            ),
        ),
    ]
