# Generated by Django 5.0.14 on 2026-10-06 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_exoneration_tva"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="reponse_client_commentaire",
            field=models.TextField(
                blank=True, editable=False, verbose_name="Commentaire du client"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="reponse_client_le",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Réponse du client le",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="reponse_client_nom",
            field=models.CharField(
                blank=True, editable=False, max_length=150, verbose_name="Signé par"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="reponse_client_par",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devis_repondus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Réponse du client par",
            ),
        ),
    ]
