# Generated by Django 5.0.14 on 2026-10-06 02:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Societe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(
                        default="Ayden Transit",
                        max_length=200,
                        verbose_name="Raison sociale",
                    ),
                ),
                (
                    "activite",
                    models.CharField(
                        blank=True,
                        default="Transit - Dédouanement - Logistique",
                        max_length=200,
                        verbose_name="Activité",
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "pays",
                    models.CharField(
                        default="Maroc", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "site_web",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Site web"
                    ),
                ),
                (
                    "ice",
                    models.CharField(blank=True, max_length=50, verbose_name="ICE"),
                ),
                (
                    "rc",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Registre de commerce (RC)",
                    ),
                ),
                (
                    "identifiant_fiscal",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Identifiant fiscal (IF)",
                    ),
                ),
                (
                    "patente",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Patente / TP"
                    ),
                ),
                (
                    "cnss",
                    models.CharField(blank=True, max_length=50, verbose_name="CNSS"),
                ),
                (
                    "capital",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Capital social"
                    ),
                ),
                (
                    "banque",
                    models.CharField(blank=True, max_length=150, verbose_name="Banque"),
                ),
                (
                    "rib",
                    models.CharField(blank=True, max_length=60, verbose_name="RIB"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to=core.models.logo_upload_path,
                        verbose_name="Logo",
                    ),
                ),
                (
                    "mentions_facture",
                    models.TextField(
                        blank=True,
                        help_text="Conditions de paiement, pénalités de retard, etc.",
                        verbose_name="Mentions en bas des factures",
                    ),
                ),
                (
                    "mentions_devis",
                    models.TextField(
                        blank=True,
                        help_text="Durée de validité, conditions d'acceptation, etc.",
                        verbose_name="Mentions en bas des devis",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Société",
                "verbose_name_plural": "Société",
            },
        ),
    ]
