# Generated by Django 5.0.14 on 2026-09-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_tiers",
                    models.CharField(
                        choices=[
                            ("client", "Client"),
                            ("fournisseur", "Fournisseur"),
                            ("transporteur", "Transporteur"),
                            ("prestataire", "Prestataire de service"),
                            ("douane", "Agent en douane"),
                            ("banque", "Banque / assurance"),
                            ("autre", "Autre"),
                        ],
                        default="client",
                        max_length=20,
                        verbose_name="Type de tiers",
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(max_length=200, verbose_name="Raison sociale"),
                ),
                (
                    "ice",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="ICE / N° d'identification",
                    ),
                ),
                (
                    "rc",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Registre de commerce"
                    ),
                ),
                (
                    "contact_principal",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Contact principal"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "ville",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "pays",
                    models.CharField(
                        default="Maroc", max_length=100, verbose_name="Pays"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client / Tiers",
                "verbose_name_plural": "Clients & Tiers",
                "ordering": ["raison_sociale"],
            },
        ),
    ]
