# Generated by Django 5.0.14 on 2026-10-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="exonere_tva",
            field=models.BooleanField(
                default=False,
                help_text="Zone franche, prestations liées à l'export, etc. Les factures et devis de ce client sont établis à 0 % de TVA.",
                verbose_name="Exonéré de TVA",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="motif_exoneration",
            field=models.CharField(
                blank=True,
                help_text="Imprimé sur les factures, ex. : « Exonération - zone franche, attestation n° ... ».",
                max_length=255,
                verbose_name="Motif / référence de l'exonération",
            ),
        ),
    ]
