# Generated by Django 5.0.14 on 2026-09-09 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dossier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="N° de dossier",
                    ),
                ),
                (
                    "reference_client",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence client"
                    ),
                ),
                (
                    "donneur_ordre",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Donneur d'ordre"
                    ),
                ),
                (
                    "type_operation",
                    models.CharField(
                        choices=[
                            ("import", "Import"),
                            ("export", "Export"),
                            ("transit", "Transit"),
                            ("douane", "Dédouanement"),
                        ],
                        max_length=20,
                        verbose_name="Type d'opération",
                    ),
                ),
                (
                    "regime_douanier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mise_consommation", "Mise à la consommation"),
                            ("admission_temporaire", "Admission temporaire"),
                            ("exportation_definitive", "Exportation définitive"),
                            ("entrepot_douanier", "Entrepôt douanier"),
                            ("transit_douanier", "Transit douanier"),
                            ("drawback", "Drawback"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Régime douanier",
                    ),
                ),
                (
                    "incoterm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXW", "EXW - Ex Works"),
                            ("FCA", "FCA - Free Carrier"),
                            ("FAS", "FAS - Free Alongside Ship"),
                            ("FOB", "FOB - Free On Board"),
                            ("CFR", "CFR - Cost and Freight"),
                            ("CIF", "CIF - Cost, Insurance and Freight"),
                            ("CPT", "CPT - Carriage Paid To"),
                            ("CIP", "CIP - Carriage and Insurance Paid To"),
                            ("DAP", "DAP - Delivered At Place"),
                            ("DPU", "DPU - Delivered at Place Unloaded"),
                            ("DDP", "DDP - Delivered Duty Paid"),
                        ],
                        max_length=5,
                        verbose_name="Incoterm",
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Origine"
                    ),
                ),
                (
                    "provenance",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Provenance"
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Destination"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("en_cours", "En cours"),
                            ("en_douane", "En douane"),
                            ("livre", "Livré"),
                            ("cloture", "Clôturé"),
                            ("annule", "Annulé"),
                        ],
                        default="ouvert",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_ouverture",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date d'ouverture"
                    ),
                ),
                (
                    "date_cloture",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de clôture"
                    ),
                ),
                ("valide", models.BooleanField(default=False, verbose_name="Validé")),
                (
                    "valide_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Validé le"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent_responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_geres",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent responsable",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dossiers",
                        to="partners.partner",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_valides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier de transit",
                "verbose_name_plural": "Dossiers de transit",
                "ordering": ["-created_at"],
            },
        ),
    ]
