# Generated by Django 5.0.14 on 2026-10-06 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("partners", "0002_exoneration_tva"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Uniquement pour le rôle « Client (portail) » : le client ne voit que ses propres dossiers.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comptes_portail",
                to="partners.partner",
                verbose_name="Société cliente (portail)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("direction", "Direction"),
                    ("agent_transit", "Agent de transit"),
                    ("comptable", "Comptable"),
                    ("consultation", "Consultation seule"),
                    ("client", "Client (portail)"),
                ],
                default="agent_transit",
                max_length=20,
            ),
        ),
    ]
