# Generated by Django 5.0.14 on 2026-10-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_portail_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="recap_alertes_email",
            field=models.BooleanField(
                default=True,
                help_text="Envoyé chaque matin s'il y a des alertes qui vous concernent (équipe uniquement).",
                verbose_name="Recevoir le récapitulatif des alertes par e-mail",
            ),
        ),
    ]
