# Generated by Django 5.0.14 on 2026-09-09 23:19

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("facture_commerciale", "Facture commerciale"),
                            ("connaissement", "Connaissement (B/L)"),
                            ("lta", "Lettre de transport aérien (LTA)"),
                            ("cmr", "Lettre de voiture (CMR)"),
                            ("packing_list", "Liste de colisage"),
                            ("certificat_origine", "Certificat d'origine"),
                            ("dau", "Déclaration en douane (DUM/DAU)"),
                            ("assurance", "Attestation d'assurance"),
                            ("autorisation", "Autorisation / licence"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Libellé"
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        upload_to=documents.models.document_upload_path,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "date_document",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date du document"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="dossiers.dossier",
                        verbose_name="Dossier",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
