# Generated by Django 5.0.14 on 2026-10-06 06:07

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="fichier",
            field=models.FileField(
                upload_to=documents.models.document_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "tif",
                            "tiff",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "csv",
                            "txt",
                        ]
                    )
                ],
                verbose_name="Fichier",
            ),
        ),
    ]
