# Generated by Django 5.0.14 on 2026-09-10 00:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
        ("partners", "0001_initial"),
        ("treasury", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, editable=False, max_length=30, unique=True
                    ),
                ),
                (
                    "reference_fournisseur",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="N° de facture fournisseur",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("recue", "Reçue"),
                            ("validee", "Validée"),
                            ("payee_partiel", "Payée partiellement"),
                            ("payee", "Payée"),
                            ("contestee", "Contestée"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_facture",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Date de la facture",
                    ),
                ),
                (
                    "date_echeance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achats",
                        to="dossiers.dossier",
                        verbose_name="Dossier",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="achats",
                        to="partners.partner",
                        verbose_name="Fournisseur / Prestataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achat / Facture fournisseur",
                "verbose_name_plural": "Achats & Factures fournisseurs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_frais",
                    models.CharField(
                        choices=[
                            ("honoraires", "Honoraires de transit"),
                            ("debours", "Débours"),
                            ("droits_taxes", "Droits et taxes"),
                            ("acconage", "Acconage"),
                            ("manutention", "Manutention"),
                            ("transport", "Transport"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Type de frais",
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Désignation"),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="purchasing.supplierinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant"
                    ),
                ),
                ("date_paiement", models.DateField(verbose_name="Date de paiement")),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces (caisse)"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("effet", "Effet de commerce"),
                            ("autre", "Autre"),
                        ],
                        default="virement",
                        max_length=15,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Référence (chèque, virement...)",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compte",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decaissements",
                        to="treasury.cashaccount",
                        verbose_name="Caisse / compte débité",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="purchasing.supplierinvoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement fournisseur",
                "verbose_name_plural": "Paiements fournisseurs",
                "ordering": ["-date_paiement"],
            },
        ),
    ]
