# Generated by Django 5.0.14 on 2026-09-09 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("dossiers", "0001_initial"),
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=150, verbose_name="Nom du compte / de la caisse"
                    ),
                ),
                (
                    "type_compte",
                    models.CharField(
                        choices=[
                            ("caisse", "Caisse (espèces)"),
                            ("banque", "Compte bancaire"),
                        ],
                        default="caisse",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="MAD", max_length=10, verbose_name="Devise"
                    ),
                ),
                (
                    "solde_initial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Solde initial",
                    ),
                ),
                (
                    "numero_compte",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="N° de compte bancaire (si applicable)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caisses_gerees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caisse / Compte de trésorerie",
                "verbose_name_plural": "Caisses & Comptes de trésorerie",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="CashTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[("entree", "Entrée"), ("sortie", "Sortie")],
                        max_length=10,
                        verbose_name="Sens",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("encaissement_client", "Encaissement client"),
                            (
                                "paiement_fournisseur",
                                "Paiement fournisseur / prestataire",
                            ),
                            (
                                "debours_dossier",
                                "Débours pour un dossier (droits, taxes...)",
                            ),
                            ("frais_generaux", "Frais généraux"),
                            ("virement_interne", "Virement interne entre comptes"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=25,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant"
                    ),
                ),
                ("date_mouvement", models.DateField(verbose_name="Date")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Libellé"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="treasury.cashaccount",
                        verbose_name="Caisse / Compte",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_caisse",
                        to="dossiers.dossier",
                        verbose_name="Dossier lié",
                    ),
                ),
                (
                    "related_payment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvement_caisse",
                        to="billing.payment",
                        verbose_name="Paiement de facture lié",
                    ),
                ),
                (
                    "tiers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_caisse",
                        to="partners.partner",
                        verbose_name="Tiers (client / fournisseur)",
                    ),
                ),
                (
                    "transfer_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="treasury.cashtransaction",
                        verbose_name="Mouvement de virement lié",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de caisse",
                "verbose_name_plural": "Mouvements de caisse",
                "ordering": ["-date_mouvement", "-created_at"],
            },
        ),
    ]
