# Generated by Django 5.0.14 on 2026-09-10 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
        ("treasury", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashtransaction",
            name="related_supplier_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mouvement_caisse",
                to="purchasing.supplierpayment",
                verbose_name="Paiement fournisseur lié",
            ),
        ),
    ]
