# Generated by Django 5.0.14 on 2026-10-06 02:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            ("changement_statut", "Changement de statut"),
                            ("eta", "ETA communiquée"),
                            ("arrivee", "Arrivée navire / avion / camion"),
                            ("dechargement", "Déchargement / mise en magasin"),
                            ("declaration", "Déclaration en douane déposée"),
                            ("visite", "Visite / contrôle douanier"),
                            ("liquidation", "Droits et taxes liquidés"),
                            ("bae", "Bon à enlever (BAE) obtenu"),
                            ("enlevement", "Enlèvement de la marchandise"),
                            ("livraison", "Livraison au client"),
                            ("incident", "Incident / blocage"),
                            ("note", "Note interne"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="Type d'événement",
                    ),
                ),
                (
                    "date_evenement",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de l'événement",
                    ),
                ),
                (
                    "lieu",
                    models.CharField(blank=True, max_length=150, verbose_name="Lieu"),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "ancien_statut",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("en_cours", "En cours"),
                            ("en_douane", "En douane"),
                            ("livre", "Livré"),
                            ("cloture", "Clôturé"),
                            ("annule", "Annulé"),
                        ],
                        max_length=20,
                        verbose_name="Ancien statut",
                    ),
                ),
                (
                    "nouveau_statut",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("en_cours", "En cours"),
                            ("en_douane", "En douane"),
                            ("livre", "Livré"),
                            ("cloture", "Clôturé"),
                            ("annule", "Annulé"),
                        ],
                        max_length=20,
                        verbose_name="Nouveau statut",
                    ),
                ),
                (
                    "automatique",
                    models.BooleanField(
                        default=False, verbose_name="Généré automatiquement"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evenements_dossier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="dossiers.dossier",
                        verbose_name="Dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement de suivi",
                "verbose_name_plural": "Événements de suivi",
                "ordering": ["-date_evenement", "-created_at"],
            },
        ),
    ]
