# Generated by Django 5.0.14 on 2026-10-06 04:04

from django.db import migrations, models


def masquer_notes_et_incidents(apps, schema_editor):
    # Existing internal notes and incidents were written before the portal existed.
    DossierEvent = apps.get_model("tracking", "DossierEvent")
    DossierEvent.objects.filter(type_evenement__in=["note", "incident"]).update(visible_client=False)


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossierevent",
            name="visible_client",
            field=models.BooleanField(
                default=True,
                help_text="Affiché sur le portail client. Les notes internes ne le sont jamais.",
                verbose_name="Visible par le client",
            ),
        ),
        migrations.RunPython(masquer_notes_et_incidents, migrations.RunPython.noop),
    ]
