# Generated by Django 5.0.14 on 2026-10-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_visible_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierevent",
            name="type_evenement",
            field=models.CharField(
                choices=[
                    ("changement_statut", "Changement de statut"),
                    ("eta", "ETA communiquée"),
                    ("arrivee", "Arrivée navire / avion / camion"),
                    ("dechargement", "Déchargement / mise en magasin"),
                    ("declaration", "Déclaration en douane déposée"),
                    ("visite", "Visite / contrôle douanier"),
                    ("liquidation", "Droits et taxes liquidés"),
                    ("bae", "Bon à enlever (BAE) obtenu"),
                    ("enlevement", "Enlèvement de la marchandise"),
                    ("livraison", "Livraison au client"),
                    ("devis_accepte", "Devis accepté par le client"),
                    ("devis_refuse", "Devis refusé par le client"),
                    ("incident", "Incident / blocage"),
                    ("note", "Note interne"),
                    ("autre", "Autre"),
                ],
                max_length=30,
                verbose_name="Type d'événement",
            ),
        ),
    ]
