# Generated by Django 5.0.14 on 2026-09-10 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("ordre", models.PositiveSmallIntegerField(verbose_name="Ordre")),
                ("libelle", models.CharField(max_length=150, verbose_name="Étape")),
                (
                    "role_requis",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("direction", "Direction"),
                            ("agent_transit", "Agent de transit"),
                            ("comptable", "Comptable"),
                            ("consultation", "Consultation seule"),
                        ],
                        max_length=20,
                        verbose_name="Rôle requis",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuvee", "Approuvée"),
                            ("refusee", "Refusée"),
                        ],
                        default="en_attente",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="Commentaire"),
                ),
                (
                    "signature_nom",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nom du signataire"
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "validateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etapes_validees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de validation",
                "verbose_name_plural": "Étapes de validation",
                "ordering": ["content_type", "object_id", "ordre"],
            },
        ),
    ]
