# Generated by Django 5.0.14 on 2026-10-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationstep",
            name="role_requis",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("direction", "Direction"),
                    ("agent_transit", "Agent de transit"),
                    ("comptable", "Comptable"),
                    ("consultation", "Consultation seule"),
                    ("client", "Client (portail)"),
                ],
                max_length=20,
                verbose_name="Rôle requis",
            ),
        ),
    ]
