# Generated by Django 5.0.14 on 2026-09-09 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dossiers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marchandise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(max_length=255, verbose_name="Désignation"),
                ),
                (
                    "code_hs",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Code SH / HS (indicatif)",
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "unite",
                    models.CharField(
                        default="colis", max_length=20, verbose_name="Unité"
                    ),
                ),
                (
                    "colisage",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Colisage"
                    ),
                ),
                (
                    "poids_brut",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Poids brut (kg)",
                    ),
                ),
                (
                    "poids_net",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Poids net (kg)",
                    ),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Valeur déclarée",
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="MAD", max_length=10, verbose_name="Devise"
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pays d'origine"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marchandises",
                        to="dossiers.dossier",
                        verbose_name="Dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marchandise / Cargo",
                "verbose_name_plural": "Marchandises / Cargo",
                "ordering": ["id"],
            },
        ),
    ]
